use crate::save_data::DataError;

/// the id of every perk in the game
#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u8)]
pub enum Perk {
    Snakey = 1,
    Kebab,
    RayGun,
    Speedy,
    Battery,
    Cheesy,
    Waffle,
    Chaotic,
    Zombie,
    Springy,
    PingPong,
    MysteryBox,
    Trophy,
    Penny,
    Meaty,
    Cubey,
    Charity,
    Candle,
    Tornado,
    Drainer,
    HouseOCards,
    Eggy,
    Buckshot,
    Void,
    Enlightened,
    Archaic,
    Warlock,
    Gourmet,
    Lunar,
    Croissant,
    JellyCroissant,
    SpicyKebab,
}

impl Perk {
    #[inline]
    pub const unsafe fn from_id_unchecked(v: u8) -> Self {
        unsafe { std::mem::transmute::<u8, Perk>(v) }
    }
}

/// the id for every item in the game
#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq, PartialOrd, Ord)]
#[repr(i16)]
pub enum Item {
    None = -1,
    Pants = 0,
    Noodle = 1,
    Cactus,
    FlameThrower,
    LobsterClaw,
    Monstrosity,
    JakeTheSnake,
    Strawberry,
    Nose,
    CrazyStraw = 9,
    EvilGoose,
    FlamingSkull,
    SeaCucumber,
    TartLard,
    Pedro,
    FlyAgaric,
    FingerPuppet,
    Jacks = 17,
    Croissant,
    Donut,
    RubberChicken,
    TonOfFeathers,
    DancingDino,
    Squirmy,
    BrokenSocket,
    RabidMonstrosity = 25,
    TestItem2,
    ToyFish,
    Flutty,
    Yeti,
    Kazoo,
    Squid,
    ThreeDGlasses,
    UraniumRod = 33,
    ThePointer,
    HappySeal,
    HotDogDog,
    FriendlyRock,
    Dave,
    TheMollusk,
    Tardigrade,
    PlasticTree = 41,
    ClayManGuy,
    Asbestos,
    CheeseHouse,
    ShishKebab,
    KidneyBean,
    WinglessFly,
    DisguiseGlasses,
    KingBaby = 49,
    PickleRat,
    MannequinHead,
    LaserPointer,
    AllSeeingPyramid,
    FishMan,
    TwoHeadedTurtle,
    InflatableDolphin,
    ProfessorPalmzy = 57,
    PregnancyTest,
    HorsePill,
    Ouroboros,
    Lentil,
    Monstrosity2, // not the upgraded version, just another copy
    WinglessFly2, // not the upgraded version, just another copy
    MysteryBoxCommon,
    PoopButt = 65,
    Alien,
    EBlock,
    PantsPlus,
    // item index 69 does not exist
    CactusPlus = 70,
    FlameThrowerPlus = 71,
    LobsterClawPlus = 72,
    MonstrosityPlus = 73,
    JakeTheSnakePlus = 74,
    // item index 75 does not exist
    NosePlus = 76,
    CrazyStrawPlus = 77,
    EvilGoosePlus = 78,
    FlamingSkullPlus = 79,
    SeaCucumberPlus = 80,
    MoldySandwich = 81,
    PedroPlus = 82,
    FlyAgaricPlus = 83,
    FingerPuppetPlus = 84,
    JacksPlus = 85,
    RubberChickenPlus = 88,
    TonOfFeathersPlus = 89,
    DancingDinosaurPlus = 90,
    SquirmyPlus = 91,
    BrokenSocketPlus = 92,
    RabidMonstrosityPlus = 93,
    Test2Plus = 94,
    ToyFishPlus,
    FluttyPlus,
    YetiPlus,
    KazooPlus,
    SquidPlus,
    ThreeDGlassesPlus,
    UraniumRodPlus,
    ThePointerPlus,
    HappySealPlus,
    FriendlyRockPlus = 105,
    MolluskPlus = 107,
    TardigradePlus,
    PlasticTreePlus,
    ClayManGuyPlus,
    AsbestosPlus,
    CheeseHousePlus,
    WinglessFlyPlus = 115,
    DisguiseGlassesPlus,
    KingBabyPlus,
    MannequinHeadPlus = 119,
    LaserPointerPlus = 120,
    AllSeeingPyramidPlus = 121,
    FishManPlus = 122,
    TwoHeadedTurtlePlus = 123,
    InflatableDolphinPlus = 124,
    ProfessorPalmyPlus = 125,
    PregnancyTestPlus = 126,
    HorsePillPlus = 127,
    OuroborosPlus = 128,
    JollyJelly = 129,
    PoopButtPlus = 133,
    AlienPlus = 134,
    EBlockPlus = 135,
    Chip = 136,
    Avocado,
    FavaBean,
    MysteryBoxRareNM = 139,
    MysteryBoxRareBM,
    MysteryBoxRareCN,
    MysteryBoxDupeNM,
    MysteryBoxUltraRareNM,
    MysteryBoxUltraRareBM,
    MysteryBoxUltraRareCM,
    Startfruit = 146,
    BrokenChip,
    SoupCrackers,
    TBlock,
    TBlockPlus,
    FlibbyFlobbies,
    FlibbyFlobbiesPlus,
    NoodlePlus,
    StrawberryPlus,
    TartLardPlus,
    CroissantPlus,
    DonutPlus,
    HotDogDogPlus,
    DavePlus,
    SishKebabPlus,
    KidneyBeanPlus,
    PickleRatPlus,
    LentilPlus,
    MoldySandwichPlus,
    JollyJellyPlus,
    ChipPlus,
    AvocadoPlus,
    FavaBeanPlus,
    StarfruitPlus,
    BrokenChipPlus,
    AntiMatter,
    BottledTears,
    BrokenFigurine,
    DollHead,
    Homunculus,
    RodentBones,
    PsychicSpider,
    TriBagel,
    TriBagelPlus,
    HairyFingore,
    HomunculusAlpha,
}

impl Item {
    #[inline]
    pub const unsafe fn from_id_unchecked(v: i16) -> Self {
        unsafe { std::mem::transmute::<i16, Item>(v) }
    }
}